/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostsExampleRouteImport } from './routes/posts-example'
import { Route as IndexRouteImport } from './routes/index'

const PostsExampleRoute = PostsExampleRouteImport.update({
  id: '/posts-example',
  path: '/posts-example',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts-example': typeof PostsExampleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts-example': typeof PostsExampleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posts-example': typeof PostsExampleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/posts-example'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/posts-example'
  id: '__root__' | '/' | '/posts-example'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsExampleRoute: typeof PostsExampleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/posts-example': {
      id: '/posts-example'
      path: '/posts-example'
      fullPath: '/posts-example'
      preLoaderRoute: typeof PostsExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsExampleRoute: PostsExampleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
